// <auto-generated />
using System;
using Chipis.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chipis.DataAccess.Migrations
{
    [DbContext(typeof(ChipisDbContext))]
    [Migration("20260312233539_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("ChatEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatEntityId");

                    b.ToTable("ChatEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatMemberEntity", b =>
                {
                    b.Property<Guid>("ChatMemberEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatMemberEntityId");

                    b.HasIndex("ChatEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ChatMemberEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("MessageEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageEntityId");

                    b.ToTable("MessageEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserEntityId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatMemberEntity", b =>
                {
                    b.HasOne("Chipis.DataAccess.Entities.ChatEntity", "ChatEntity")
                        .WithMany()
                        .HasForeignKey("ChatEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chipis.DataAccess.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatEntity");

                    b.Navigation("UserEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
