// <auto-generated />
using System;
using Chipis.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chipis.DataAccess.Migrations
{
    [DbContext(typeof(ChipisDbContext))]
    [Migration("20260315180622_token")]
    partial class token
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("ChatEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatEntityId");

                    b.ToTable("ChatEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatMemberEntity", b =>
                {
                    b.Property<Guid>("ChatMemberEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatMemberEntityId");

                    b.HasIndex("ChatEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ChatMemberEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("MessageEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderUserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageEntityId");

                    b.HasIndex("ChatEntityId");

                    b.HasIndex("SenderUserEntityId");

                    b.ToTable("MessageEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("RefreshTokenEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("RefreshTokenEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserEntityId");

                    b.HasIndex("Telephone")
                        .IsUnique();

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.ChatMemberEntity", b =>
                {
                    b.HasOne("Chipis.DataAccess.Entities.ChatEntity", "ChatEntity")
                        .WithMany()
                        .HasForeignKey("ChatEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chipis.DataAccess.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.MessageEntity", b =>
                {
                    b.HasOne("Chipis.DataAccess.Entities.ChatEntity", "ChatEntity")
                        .WithMany()
                        .HasForeignKey("ChatEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chipis.DataAccess.Entities.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatEntity");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Chipis.DataAccess.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Chipis.DataAccess.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
